server:
  port: 8510

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/leeshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
type-aliases-package: com.clt.chenshop.common.pojo
mapper-locations: classpath:mapper/*.xml

dubbox:
  application:
    name: chenshop-service-admin
    organization: dubbox
    owner: clt
  registry:
    protocol: zookeeper
    address: 192.168.162.128:2181
  annotation:
    package: com.clt.chenshop.service.admin
  protocol:
    name: dubbo
    port: 20880
    timeout: 30000
    threadpool: fixed
    threads: 500
    accepts: 1000
    serialization: kryo
    optimizer: com.clt.chenshop.common.serial.SerializationOptimizerImpl